# Workflow for executing androidTests of Checkout Example app on Browserstack App Automate

name: "ACTION: Test example-checkout on App Automate"

on:
  workflow_dispatch:

jobs:
  test-app-automate:
    name: Test example-checkout on App Automate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean example-checkout project
        run: ./gradlew clean
      - name: Test example-checkout on App Automate
        env:
          MOBILE_MERCHANT_CODE: ${{ secrets.MOBILE_MERCHANT_CODE }}
          MOBILE_MERCHANT_PAYMENT_TOKEN: ${{ secrets.MOBILE_MERCHANT_PAYMENT_TOKEN }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          PAYMENTAPI_LISTURL: ${{ secrets.PAYMENTAPI_LISTURL }}
        run: ./gradlew :example-checkout:executeTestsOnAppAutomate