name: Cleanup Browserstack

on:
  pull_request:
    types:
      - converted_to_draft
      - closed

jobs:
  delete-from-app-live:
    name: Delete example-checkout from App Live
    # Don't clean binaries for PRs where head (from) branch is develop or master to avoid double deletion
    if: github.head_ref != 'develop' && github.head_ref != 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Delete example-checkout from App Live
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: ./gradlew deleteExampleCheckoutFromAppLive