# Workflow for testing and publishing of the snapshot checkout artifact

name: Publish snapshot artifact
on:
  push:
    branches:
      - "develop"

jobs:
  test-checkout:
    name: Test checkout module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Run Checkout unit-tests
        run: ./gradlew testCheckout

  test-example:
    name: Test example apps
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Test example on Browserstack
        env:
          MOBILE_MERCHANT_CODE: ${{ secrets.MOBILE_MERCHANT_CODE }}
          MOBILE_MERCHANT_PAYMENT_TOKEN: ${{ secrets.MOBILE_MERCHANT_PAYMENT_TOKEN }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          PAYMENTAPI_LISTURL: ${{ secrets.PAYMENTAPI_LISTURL }}
        run: ./gradlew testExampleCheckoutOnAppAutomate

  test-paymentservices:
    name: Test payment services
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build payment services
        run: ./gradlew buildPaymentServices
      - name: Run payment service unit-tests
        run: ./gradlew testPaymentServices

  test-riskproviders:
    name: Test risk providers
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build risk providers
        run: ./gradlew buildRiskProviders
      - name: Run Risk Providers unit-tests
        run: ./gradlew testRiskProviders

  publish-checkout:
    needs: [ test-example, test-paymentservices, test-riskproviders ]
    name: Publish checkout snapshot artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Publish checkout artifact
        env:
          NEXUS_USER: ${{ secrets.NEXUS_ARTIFACT_ROOT_ACCESS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_ARTIFACT_ROOT_ACCESS_PASSWORD }}
        run: ./gradlew publishCheckoutSnapshotVersion

  upload-examplecheckout:
    needs: [ test-example, test-paymentservices, test-riskproviders ]
    name: Upload ExampleCheckout to Browserstack AppLive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Upload ExampleCheckout to Browserstack AppLive
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: ./gradlew uploadExampleCheckoutToAppLive

  publish-paymentservices:
    needs: publish-checkout
    name: Publish payment service snapshot artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Publish payment service artifacts
        env:
          NEXUS_USER: ${{ secrets.NEXUS_ARTIFACT_ROOT_ACCESS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_ARTIFACT_ROOT_ACCESS_PASSWORD }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: ./gradlew publishPaymentServicesSnapshotVersion

  publish-riskproviders:
    needs: publish-checkout
    name: Publish risk provider snapshot artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Publish risk provider artifacts
        env:
          NEXUS_USER: ${{ secrets.NEXUS_ARTIFACT_ROOT_ACCESS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_ARTIFACT_ROOT_ACCESS_PASSWORD }}
        run: ./gradlew publishRiskProvidersSnapshotVersion