# Workflow for building snapshot versions of the Android Checkout SDK.

name: Build workflow

on:
  push:
    branches:
      - "develop"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean Android Checkout SDK
        run: ./gradlew clean
      - name: Build Checkout module
        run: ./gradlew buildCheckout

  test:
    needs: build
    name: "Test"
    environment: Browserstack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean Android Checkout SDK
        run: ./gradlew clean
      - name: Run Checkout unit-tests
        run: ./gradlew testCheckout
      - name: Test example apps on Browserstack
        env:
          MOBILE_MERCHANT_CODE: ${{ secrets.MOBILE_MERCHANT_CODE }}
          MOBILE_MERCHANT_PAYMENT_TOKEN: ${{ secrets.MOBILE_MERCHANT_PAYMENT_TOKEN }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          PAYMENTAPI_LISTURL: ${{ secrets.PAYMENTAPI_LISTURL }}
        run: ./gradlew testExampleApps

  publish:
    needs: test
    name: "Publish"
    environment: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Clean Android Checkout SDK
      run: ./gradlew clean
    - name: Publish checkout module
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      run: ./gradlew publishCheckout