# Workflow for generating coverage report for Checkout module

name: "ACTION: Coverage report for Checkout module"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Generate coverage report
        run: ./gradlew generateCoverageReportForCheckout
      - name: Load code coverage report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.6
        with:
          coverage_results_path: checkout/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: true
          minimum_coverage: 25
          fail_below_threshold: false
          publish_only_summary: true
      - name: Add coverage to summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
