# Workflow for publishing the Checkout Example app to GooglePlay

name: "ACTION: Upload example-checkout to GooglePlay"

on:
  workflow_dispatch:

jobs:
  upload-play-store:
    name: Upload example-checkout to GooglePlay
    runs-on: macos-latest
    environment:
      name: Googleplay

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install dependencies specified in Gemfile
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Prepare keystore
        id: keystore-generator
        env:
          PLAYSTORE_UPLOAD_STOREFILE_BASE64: ${{ secrets.PLAYSTORE_UPLOAD_STOREFILE_BASE64 }}
        run: |
          # Keystore
          KEYSTORE_PATH=$RUNNER_TEMP/keystore.jks
          echo -n "$PLAYSTORE_UPLOAD_STOREFILE_BASE64" | base64 --decode --output $KEYSTORE_PATH
          echo "::set-output name=KEYSTORE_FILE::$KEYSTORE_PATH"
      - name: Prepare upload json
        id: upload-json-generator
        env:
          PLAYSTORE_JSON_KEY_FILE_BASE64: ${{ secrets.PLAYSTORE_JSON_KEY_FILE_BASE64 }}
        run: |
          UPLOAD_JSON_PATH=$RUNNER_TEMP/upload.json
          echo -n "$PLAYSTORE_JSON_KEY_FILE_BASE64" | base64 --decode --output $UPLOAD_JSON_PATH
          echo "::set-output name=UPLOAD_JSON_FILE::$UPLOAD_JSON_PATH"
      - name: Build and upload example-checkout to GooglePlay
        env:
          PLAYSTORE_JSON_KEY_FILE: ${{ steps.upload-json-generator.outputs.UPLOAD_JSON_FILE }}
          PLAYSTORE_UPLOAD_STOREFILE: ${{ steps.keystore-generator.outputs.KEYSTORE_FILE }}
          PLAYSTORE_UPLOAD_STOREPASSWORD: ${{ secrets.PLAYSTORE_UPLOAD_STOREPASSWORD }}
          PLAYSTORE_UPLOAD_KEYALIAS: ${{ secrets.PLAYSTORE_UPLOAD_KEYALIAS }}
          PLAYSTORE_UPLOAD_KEYPASSWORD: ${{ secrets.PLAYSTORE_UPLOAD_KEYPASSWORD }}
        run: bundle exec fastlane uploadCheckoutExample