# Workflow for running tests triggered by pull requests

name: Test pull request
on:
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]

jobs:
  test-checkout:
    name: Test checkout module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Run checkout unit-tests
        run: ./gradlew testCheckout

  test-examples:
    name: Test example apps
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Test examples on Browserstack
        env:
          MOBILE_MERCHANT_CODE: ${{ secrets.MOBILE_MERCHANT_CODE }}
          MOBILE_MERCHANT_PAYMENT_TOKEN: ${{ secrets.MOBILE_MERCHANT_PAYMENT_TOKEN }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          PAYMENTAPI_LISTURL: ${{ secrets.PAYMENTAPI_LISTURL }}
        run: ./gradlew testExampleAppsOnAppAutomate

  test-paymentservices:
    name: Test payment services
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build payment services
        run: ./gradlew buildPaymentServices
      - name: Run payment service unit-tests
        run: ./gradlew testPaymentServices

  test-riskproviders:
    name: Test risk providers
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build risk providers
        run: ./gradlew buildRiskProviders
      - name: Run risk provider unit-tests
        run: ./gradlew testRiskProviders

  upload-examplecheckout:
    needs: [ test-examples, test-paymentservices, test-riskproviders ]
    name: Upload ExampleCheckout to Browserstack AppLive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Upload ExampleCheckout to Browserstack AppLive
        env:
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        run: ./gradlew uploadExampleCheckoutToAppLive
