# Workflow for running tests triggered by pull requests

name: Test pull request
on:
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]

jobs:
  test-checkout:
    name: Test checkout module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Run checkout unit-tests
        run: ./gradlew testCheckout

  test-riskproviders:
    name: Test Risk Providers
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Run Risk Providers unit-tests
        run: ./gradlew testRiskProviders