# Workflow for running tests triggered by pull requests in the Android Checkout SDK

name: Test Pull Request
on:
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]

jobs:
  test:
    name: "Test checkout module"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Run checkout unit-tests
        run: ./gradlew testCheckout