# Workflow for testing and publishing of the release checkout artifact

name: Publish release artifact
on:
  push:
    branches:
      - "master"
jobs:

  test-checkout:
    name: Test checkout module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Run Checkout unit-tests
        run: ./gradlew testCheckout

  test-examples:
    name: Test example apps
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Test examples on Browserstack
        env:
          MOBILE_MERCHANT_CODE: ${{ secrets.MOBILE_MERCHANT_CODE }}
          MOBILE_MERCHANT_PAYMENT_TOKEN: ${{ secrets.MOBILE_MERCHANT_PAYMENT_TOKEN }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          PAYMENTAPI_LISTURL: ${{ secrets.PAYMENTAPI_LISTURL }}
        run: ./gradlew testExampleAppsOnAppAutomate

  test-riskproviders:
    name: Test Risk Providers
    needs: test-checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Clean checkout project
      run: ./gradlew clean
    - name: Run Risk Providers unit-tests
      run: ./gradlew testRiskProviders

  release:
    needs: [test-examples, test-riskproviders]
    runs-on: ubuntu-latest
    name: Create release tag
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: version
        run: echo "::set-output name=version::$(<VERSIONNAME)"
        id: version
      - name: Create release tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          body_path: CHANGELOG.rst
          draft: false
          prerelease: false

  publish-checkout:
    needs: release
    name: Publish release artifact
    environment: Packagecloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean project
        run: ./gradlew clean
      - name: Publish release artifact
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: ./gradlew publishCheckoutReleaseVersion

  publish-riskproviders:
    needs: [ publish-checkout, test-riskproviders ]
    name: Publish Risk Providers release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Publish Risk Provider artifacts
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publishRiskProvidersReleaseVersion