# Workflow for executing androidTests of Checkout Example app on Browserstack App Automate

name: ACTION Test Example-Checkout on App Automate

on:
  workflow_dispatch:

jobs:
  test-app-automate:
    name: Test on App Automate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Test on App Automate
        run: ./gradlew :example-checkout:executeTestsOnAppAutomate