# Workflow for running tests triggered by pull requests in the Android Checkout SDK

name: Test workflow

on:
  pull_request:
    types: [ opened, reopened, labeled, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Clean Android Checkout SDK
        run: ./gradlew clean
      - name: Build checkout module
        run: ./gradlew buildCheckout
      - name: Test checkout module
        run: ./gradlew testCheckout