# Workflow for releasing the Android Checkout SDK

name: Test
on:
  push:
    branches:
      - "develop"
jobs:
  version:
    runs-on: ubuntu-latest
    name: "Version"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Remove Snapshot from version
        run: |
          ./gradlew createTestList
          git add './shared-test/lists/test.json'
          git commit --message "Test commit from pull request"
          git push