# Workflow for publishing the Shop Example app to Browserstack App Live

name: "ACTION: Upload example-shop to App Live"

on:
  workflow_dispatch:

jobs:
  upload-app-live:
    name: Upload to App Live
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean checkout project
        run: ./gradlew clean
      - name: Upload to App Live
        run: ./gradlew :example-shop:uploadToAppLive